### PR TITLE
Merge pull request #1 from LDmicro/feature/JG52a

### PR DESCRIPTION
**Pull request by joegil95**
Feature/jg52a

### CODE REVIEW

**Comment by LDmicroGitHub** [comment]
Yes, I see the pull request. Change file or Add a new file and I can receive it.

**Comment by joegil95** [comment]
OK

I've just uploaded my files to:
Joegil95/LDmicro/feature/JG52a

3 .cpp files
1 .h file
2 lang .txt files
15 info .txt files in LIBRARIES

Do you have any idea about error 1400 in UART ?

Good evening
José



----- Mail original -----
De: "LDmicroGitHub" <notifications@github.com>
À: "LDmicro/LDmicro" <LDmicro@noreply.github.com>
Cc: "joegil95" <jose.gilles@free.fr>, "State change" <state_change@noreply.github.com>
Envoyé: Jeudi 21 Février 2019 19:25:46
Objet: Re: [LDmicro/LDmicro] Merge pull request #1 from LDmicro/feature/JG52a (#159)



Yes, I see the pull request. Change file or Add a new file and I can receive it.

**Comment by LDmicroGitHub** [comment]
>>Do you have any idea about error 1400 in UART ?
I will resolve this.

**Comment by LDmicroGitHub** [comment]
maincontrols.cpp
...
    AppendMenu(ConMenu, MF_STRING, MNU_MAKE_NORMAL, _("Make &Normal\tN"));
    AppendMenu(ConMenu, MF_STRING, MNU_NEGATE, _("Make &Negated\tN"));
...
There is no problem with Normal-Negate functionality placed on one 'N' key. When Coil or Contact are selected 'N' key change the negation property. It's comfortable to use.

'A' key execute "Insert &A/D Converter Read" menu.

**Comment by LDmicroGitHub** [comment]
Removed lang-tables.h
lang-tables.h created automatically from source code and should not be managed by.Version Control System(Git).

'lang-tables.h' is created by 'lang-tables.pl'

'lang-tables.pl' is called from 'makefile'
...
$(OBJDIR)/lang-tables.h: lang*.txt
    $(PERL) lang-tables.pl > $(OBJDIR)/lang-tables.h
...

**Comment by LDmicroGitHub** [comment]
PlcProgram.cpp
...
void PlcProgram::setMcu(McuIoInfo* m)
{
  ...
    configurationWord = 0;     ///// Added by JG
....
}

void PlcProgram::reset()
{
...
    configurationWord = 0;
    setMcu(nullptr);
}

There is 
configurationWord = 0;
in PlcProgram::reset()

and PlcProgram.cpp is much reorganized.

**Pull request merged**
